### ISSUE TITLE
[get_corpus.sh] the link for the corpus seems to be invalid

### ISSUE THREAD

**Issue by liuph0119** [gbcolborne/hypernym_discovery#3] opened 2022-02-23 07:57 UTC
hi, thanks for your excellent work. I found that the link for the corpus seems to be invalid during my reproduction. Is there any other way to get it?

**Comment by gbcolborne** [comment] 2022-02-23 12:59
I was able to download it using a browser. Try this link: https://docs.google.com/uc?export=download&id=0Bz40_IukD5qDV0RsWUtDcDlYU2c.

**Comment by gbcolborne** [comment] 2022-02-23 13:00
Closing this issue, as link works in a browser.

**Closed as completed by gbcolborne** 2022-02-23 13:00 UTC

**Comment by cgf1986** [comment] 2022-05-26 07:37
Hi thank you very much for sharing this work!. I have the same issue when running get_corpus.sh. Is it still possible to download the corpus from that link?.

**Comment by gbcolborne** [comment] 2022-05-26 15:31
It looks like it is no longer possible to `wget` the corpora, or at least the command I had found no longer works. I think it's because the `sed` pattern now fails to find the necessary cookie in the output of the inner `wget`, so maybe Google no longer exposes this. I would probably have to use [gdown](https://github.com/wkentaro/gdown) or something like that, but I don't have time to work on this at the moment. 

I can confirm that the corpora can still be downloaded using a browser, at the following links:

* 1A: https://docs.google.com/uc?export=download&id=0Bz40_IukD5qDV0RsWUtDcDlYU2c
* 1B: https://docs.google.com/uc?export=download&id=0Bz40_IukD5qDdktiRnh3MjhyYWc
* 1C: https://docs.google.com/uc?export=download&id=0Bz40_IukD5qDeUNOUFpuRjFzOGM
* 2A: https://docs.google.com/uc?export=download&id=0Bz40_IukD5qDekY2RXk0ekJRRGc
* 2B: https://docs.google.com/uc?export=download&id=0Bz40_IukD5qDUElXUnZ4YlJVYW8

Hope this helps.
